services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=ejemplo
      - POSTGRES_USER=santiago
      - POSTGRES_PASSWORD=santiago
    
    ports:
      - '5432:5432'
    volumes:
      - ./postgres_data:/var/lib/postgresql 


